### ISSUE TITLE
The 'Install Augurk CLI' task does not fix augurk-cli demand

### ISSUE THREAD

**Issue by simondel** [Augurk/vsts-extension#9]
The task 'Install Augurk CLI' does not set/remove the augurk-cli demand for agents. This makes it difficult to get builds to start for the first time:
![image](https://user-images.githubusercontent.com/4221997/56130731-06738080-5f86-11e9-9979-f39be19178ea.png)

The build pipeline (with locked augurk-cli demand):
![image](https://user-images.githubusercontent.com/4221997/56130833-4175b400-5f86-11e9-89d4-bfa9f5362927.png)

**Comment by jmezach** [comment]
That's interesting, because I would expect [this](https://github.com/Augurk/vsts-extension/blob/89b921122c0f204cdba919a2f4adefbfe7cf7f12/src/build-task/AugurkCLIInstaller/task.json#L13) to fill that requirement as documented [here](https://github.com/Microsoft/azure-pipelines-tool-lib/blob/master/docs/overview.md#capabilities).

**Comment by jmezach** [comment]
@simondel I ran into this issue myself recently as well. It looks like this only works as expected for Hosted agents, but not for any self-hosted agents. Interestingly adding the capability to a self-hosted agent without setting any value does work. I guess that's a workaround, but it is far from ideal. Unfortunately there isn't much we can do here. This must be fixed on the Azure DevOps side. I'll see if I can file an issue there, but will close this.
